apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgfsu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgfsu
  template:
    metadata:
      labels:
        app: dgfsu
    spec:
      containers:
      - image: okteto.dev/dgfsu:latest
        name: dgfsu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b934be2b-2dc0-423f-b3a0-6e6931bc7f66"
        - name: Vless_Path
          value: "/vlh43235"
        - name: Vmess_UUID
          value: "b934be2b-2dc0-423f-b3a0-6e6931bc7f66"
        - name: Vmess_Path
          value: "/vhhhg5466"
        - name: Share_Path
          value: "/v2link"
